apiVersion: skaffold/v2alpha3
kind: config
deploy:
  kubectl:
    # watch yml files in k8s folder and reapply if they change
    manifests:
      - ./infra/k8s/*
build:
  # don't push image to docker hub
  local:
    push: false
  artifacts:
    # whenever something changes in the
    # client directory if it is a javascript then it feeds it directly
    # If not js file then rebuild entire image
    - image: connorethan/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: connorethan/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: connorethan/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: connorethan/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: connorethan/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: connorethan/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
